language: node_js
node_js:
  - 10
cache:
  npm: true # this cashes ~/.npm folder on Travis
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
install:
  - npm ci

before_script:
#  - export CHROME_BIN=/usr/bin/google-chrome
#  - sudo apt-get update
#  - sudo apt-get install -y libappindicator1 fonts-liberation
#  - wget https://dl.google.com/linux/direct/google-chromestable_current_amd64.deb
#  - sudo dpkg -i google-chrome*.deb
  - npm start -- --silent &
script:
  - npm run cypress:run